In [ ]:
import pandas as pd
import nltk
import re
from nltk.stem import WordNetLemmatizer 
nltk.download('popular')

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection popular

True

In [ ]:
data=pd.read_parquet('/content/drive/MyDrive/6195/2021-01')

In [ ]:
data

,id,tweet_id,headline,translated_headline,date,link,timestamp,link_hash,is_starred_by_the_tie,metadata,tags,sources,starred_by_the_tie_user
0,159224,NaN,Can a SIP make cryptocurrencies less risky for...,None,2021-01-01 00:00:00+00:00,https://economictimes.indiatimes.com/markets/s...,2021-01-01 02:05:03+00:00,45078deba48d2dfce5a6dceed5164ad5,False,None,"[{'coin': None, 'id': 226, 'name': 'Crypto', '...","[{'collections': [{'id': 39, 'name': 'Mainstre...",None
1,159223,NaN,United States v. 391.5873617 in Bitcoin,None,2021-01-01 00:00:00+00:00,https://courtlistener.com/docket/26980116/2/un...,2021-01-01 11:10:05+00:00,9a89b86414bf3afad66f019a14878fb0,False,None,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...","[{'collections': [{'id': 3, 'name': 'Court Cas...",None
2,159222,NaN,2:20-cv-10676 Christopher Brown v. Damon Dash ...,None,2021-01-01 00:00:00+00:00,https://ecf.cacd.uscourts.gov/cgi-bin/DktRpt.p...,2021-01-01 23:31:04+00:00,8a0b3174bd318ff129f4877d1a3375e0,False,None,"[{'coin': {'name': 'Dash', 'ticker': 'DASH', '...","[{'collections': [{'id': 3, 'name': 'Court Cas...",None
3,159221,NaN,Record in a matter of hours! Bitcoin price exc...,None,2021-01-02 00:00:00+00:00,http://feedproxy.google.com/~r/entrepreneur/la...,2021-01-02 20:45:09+00:00,7ab81cac810617f051ec5a7e5f7305cb,False,None,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...","[{'collections': [{'id': 24, 'name': 'Traditio...",None
4,159220,NaN,"Bitcoin rallies above $30,000 for first time",None,2021-01-03 00:00:00+00:00,https://economictimes.indiatimes.com/markets/s...,2021-01-03 04:35:04+00:00,7b7761bfc90116deb2ec784fe85b1728,False,None,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...","[{'collections': [{'id': 39, 'name': 'Mainstre...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6366,423123,NaN,ICON Development Roadmap Update‚Ää‚Äî‚ÄäJanuary 2021,None,2021-01-31 00:00:00+00:00,https://medium.com/helloiconworld/icon-develop...,2021-01-31 23:17:08+00:00,6d0ca2b0193a3082d44928758439132c,False,None,"[{'coin': {'name': 'ICON', 'ticker': 'ICX', 'u...","[{'collections': [{'id': 7, 'name': 'Direct fr...",None
6367,163587,NaN,US Lawmaker Likes Bitcoin ‚Äî Urges Policymakers...,None,2021-01-31 00:00:00+00:00,https://news.bitcoin.com/us-lawmaker-likes-bit...,2021-01-31 23:32:06+00:00,bf4ba190b08a0da49691c2bdc91d52e1,False,None,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...","[{'collections': [{'id': 5, 'name': 'Crypto Na...",None
6368,163586,NaN,Bitcoin subreddit hits 2M subscribers followin...,None,2021-01-31 00:00:00+00:00,https://cointelegraph.com/news/bitcoin-subredd...,2021-01-31 23:32:07+00:00,bcccde572c5c740a7bd62f0ee15a5ffb,False,None,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...","[{'collections': [{'id': 5, 'name': 'Crypto Na...",None
6369,163588,1.356024e+18,"üêï Learn about #DOGE, the meme-inspired coin th...",None,2021-01-31 00:00:00+00:00,https://twitter.com/krakenfx/status/1356023963...,2021-01-31 23:38:16+00:00,d4643c999a05bf9f78a8a0f2a83e420f,False,None,"[{'coin': {'name': 'Dogecoin', 'ticker': 'DOGE...","[{'collections': [{'id': 43, 'name': 'Exchange...",None
6370,423122,1.356024e+18,"üêï Learn about #DOGE, the meme-inspired coin th...",None,2021-01-31 00:00:00+00:00,https://twitter.com/i/web/status/1356023963839...,2021-01-31 23:47:40.797000+00:00,b8fbfb655179a0ff989ca58f3494a7db,False,None,"[{'coin': {'name': 'Dogecoin', 'ticker': 'DOGE...","[{'collections': [{'id': 43, 'name': 'Exchange...",None

In [ ]:
data=data[['id','date','headline', 'timestamp', 'tags']]

In [ ]:
data['hashtag'] = data['headline'].apply(lambda x: re.findall(r"#(\w+)", x))
data['hashtag']

<ipython-input-7-57e215a67ce5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['hashtag'] = data['headline'].apply(lambda x: re.findall(r"#(\w+)", x))

0           []
1           []
2           []
3           []
4           []
         ...
6366        []
6367        []
6368        []
6369    [DOGE]
6370    [DOGE]
Name: hashtag, Length: 6371, dtype: object

–õ–µ–º–º–∞—Ç–∏–∑–∞—Ü–∏—è, –ø—Ä–∏–≤–µ–¥–µ–Ω–∏–µ –∫ –Ω–∏–∂–Ω–µ–º—É —Ä–µ–≥–∏—Å—Ç—Ä—É

In [ ]:
lemmatizer = WordNetLemmatizer()

In [ ]:
for i in range(len(data['headline'])):
  data['headline'][i]=(lemmatizer.lemmatize( data['headline'][i])).lower()

<ipython-input-9-41e9ffc3d8d8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['headline'][i]=(lemmatizer.lemmatize( data['headline'][i])).lower()

In [ ]:
data['headline'].head()

0    can a sip make cryptocurrencies less risky for...
1              united states v. 391.5873617 in bitcoin
2    2:20-cv-10676 christopher brown v. damon dash ...
3    record in a matter of hours! bitcoin price exc...
4         bitcoin rallies above $30,000 for first time
Name: headline, dtype: object

—É–¥–∞–ª–µ–Ω–∏–µ –∑–Ω–∞–∫–æ–≤ –ø—Ä–µ–ø–∏–Ω–∞–Ω–∏—è –∏ —Ü–∏—Ñ—Ä

In [ ]:
for i in range(len(data)):
    data.headline[i] = re.sub(r'[^\w\s]', '', data.headline[i])
    data.headline[i] = re.sub(r'[\d]', '', data.headline[i])
data.head()

<ipython-input-11-313465fc948e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.headline[i] = re.sub(r'[^\w\s]', '', data.headline[i])
<ipython-input-11-313465fc948e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.headline[i] = re.sub(r'[\d]', '', data.headline[i])

,id,date,headline,timestamp,tags,hashtag
0,159224,2021-01-01 00:00:00+00:00,can a sip make cryptocurrencies less risky for...,2021-01-01 02:05:03+00:00,"[{'coin': None, 'id': 226, 'name': 'Crypto', '...",[]
1,159223,2021-01-01 00:00:00+00:00,united states v in bitcoin,2021-01-01 11:10:05+00:00,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...",[]
2,159222,2021-01-01 00:00:00+00:00,cv christopher brown v damon dash et al,2021-01-01 23:31:04+00:00,"[{'coin': {'name': 'Dash', 'ticker': 'DASH', '...",[]
3,159221,2021-01-02 00:00:00+00:00,record in a matter of hours bitcoin price exce...,2021-01-02 20:45:09+00:00,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...",[]
4,159220,2021-01-03 00:00:00+00:00,bitcoin rallies above for first time,2021-01-03 04:35:04+00:00,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...",[]

–£–¥–∞–ª–µ–Ω–∏–µ —Å—Ç–æ–ø-—Å–ª–æ–≤ –∏ —Ç–æ–∫–µ–Ω–∏–∑–∞—Ü–∏—è

In [ ]:
from nltk.corpus import stopwords

In [ ]:
for i in range(len(data)):
    temp_tokenize = []
    str_tokenize = ''
    temp_tokenize += nltk.word_tokenize(data.headline[i])
    for j in range(len(temp_tokenize)):
        if temp_tokenize[j] not in stopwords.words('english'):
            str_tokenize += temp_tokenize[j]
        if (j < len(temp_tokenize)):
            str_tokenize += ' '
    data.headline[i] = str_tokenize
data.head()

<ipython-input-13-af6ebb201420>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.headline[i] = str_tokenize

,id,date,headline,timestamp,tags,hashtag
0,159224,2021-01-01 00:00:00+00:00,sip make cryptocurrencies less risky indian...,2021-01-01 02:05:03+00:00,"[{'coin': None, 'id': 226, 'name': 'Crypto', '...",[]
1,159223,2021-01-01 00:00:00+00:00,united states v bitcoin,2021-01-01 11:10:05+00:00,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...",[]
2,159222,2021-01-01 00:00:00+00:00,cv christopher brown v damon dash et al,2021-01-01 23:31:04+00:00,"[{'coin': {'name': 'Dash', 'ticker': 'DASH', '...",[]
3,159221,2021-01-02 00:00:00+00:00,record matter hours bitcoin price exceeds,2021-01-02 20:45:09+00:00,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...",[]
4,159220,2021-01-03 00:00:00+00:00,bitcoin rallies first time,2021-01-03 04:35:04+00:00,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...",[]

–°—Ç–µ–º–º–∏–Ω–≥

In [ ]:
from nltk.stem.snowball import SnowballStemmer

In [ ]:
sno = nltk.stem.SnowballStemmer('english')
sno.stem('grows')

'grow'

In [ ]:
words=[]
words=data.headline[0].split(' ')

In [ ]:
words[0]

'learn'

In [ ]:
test_stemming = []
for i in range(len(data)): 
    words=data.headline[i].split(' ')
    new_str=''
    for j in range(len(words)):
      words[j]=sno.stem(words[j])
      new_str+=words[j]+' '
    #print(new_str)
    data.headline[i]=new_str

<ipython-input-31-dd371e457011>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.headline[i]=new_str

In [ ]:
data.head()

,id,date,headline,timestamp,tags,hashtag
0,159224,2021-01-01 00:00:00+00:00,sip make cryptocurr less riski indian inves...,2021-01-01 02:05:03+00:00,"[{'coin': None, 'id': 226, 'name': 'Crypto', '...",[]
1,159223,2021-01-01 00:00:00+00:00,unit state v bitcoin,2021-01-01 11:10:05+00:00,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...",[]
2,159222,2021-01-01 00:00:00+00:00,cv christoph brown v damon dash et al,2021-01-01 23:31:04+00:00,"[{'coin': {'name': 'Dash', 'ticker': 'DASH', '...",[]
3,159221,2021-01-02 00:00:00+00:00,record matter hour bitcoin price exceed,2021-01-02 20:45:09+00:00,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...",[]
4,159220,2021-01-03 00:00:00+00:00,bitcoin ralli first time,2021-01-03 04:35:04+00:00,"[{'coin': {'name': 'Bitcoin', 'ticker': 'BTC',...",[]

–°–æ—Ö—Ä–∞–Ω—è–µ–º –æ–±—Ä–∞–±–æ—Ç–∞–Ω–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ

In [ ]:
import pickle

In [ ]:
with open('test_stemming.pkl', 'wb') as output_file: 
    pickle.dump(test_stemming, output_file, protocol=pickle.HIGHEST_PROTOCOL)